# Generated by Django 4.0.6 on 2022-07-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price of item',
            new_name='price',
        ),
    ]
